name: "Set NPM Token Action"
description: "Creates a .npmrc file with your NPM token inside it."
inputs:
  token:
    description: "your npm token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
